services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"


  db:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: magazine_db
      POSTGRES_USER: magazine_user
      POSTGRES_PASSWORD: 2532
    ports:
      - "${FAST__APP__DB__PORT}:${FAST__APP__DB__PORT}"
volumes:
  postgres_data: