services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "${FAST__APP__PORT}:${FAST__APP__PORT}"
    depends_on:
      - db
      - redis

  redis:
    image: redis:8-alpine
    ports:
      - "${FAST_APP_REDIS_PORT}:${FAST_APP_REDIS_PORT}"


  db:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${FAST__APP__DB__NAME}
      POSTGRES_USER: ${FAST__APP__DB__USER}
      POSTGRES_PASSWORD: ${FAST__APP__DB__PASSWORD}
    ports:
      - "${FAST__APP__DB__PORT}:${FAST__APP__DB__PORT}"
volumes:
  postgres_data: